- name: "Install asdf plugins"
  shell: |
    asdf plugin-add {{ item }} || exit 0
  with_items:
    - java
    - nodejs
  tags:
    - work
    - personal
    - asdf

- name: "Install Default Node"
  shell: |
    asdf install nodejs latest:18
    asdf global nodejs latest:18
  tags:
    - work
    - personal
    - asdf
