- name: Install config manager - Chezmoi
  homebrew:
    name: chezmoi
    state: present
  tags:
    - work
    - personal
    - dotfiles

- name: Cloning .dotfiles
  script: "{{ playbook_dir | dirname + '/ansible/chezmoi.sh'}}"
  tags:
    - work
    - personal
    - dotfiles
