- name: Get Packer
  ignore_errors: true
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - work
    - personal
    - neovim

- name: Pull my nvim config
  ignore_errors: true
  ansible.builtin.git:
    repo: 'https://github.com/povkas/nvim'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
  tags:
    - install
    - work
    - personal
    - neovim
