- name: Install Yarn
  npm:
    name: yarn
    global: yes
  tags:
    - work
    - personal
    - npm-packages

- name: Install eslint
  npm:
    name: eslint
    global: yes
  tags:
    - work
    - personal
    - npm-packages

- name: Install Typescript
  npm:
    name: typescript
    global: yes
  tags:
    - work
    - personal
    - npm-packages

- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  tags:
    - work
    - personal
    - npm-packages
