- name: Clone powerlevel repo
  ignore_errors: true
  ansible.builtin.command:
    cmd: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k"
  environment:
    ZSH_CUSTOM: "{{ lookup('env', 'ZSH_CUSTOM') }}"
  tags:
    - work
    - personal
    - powerlevel
  become: yes
  become_user: "{{ become_user | default(ansible_env.USER) }}"
